### ISSUE TITLE
language configuration

### ISSUE THREAD

**Issue by aitnasser** [tobyn/angular-stripe-checkout#10]
Stripe released a feature that allows you to haveStripe **Checkout display in other languages**<br> (Japanese, German, French, Simplified Chinese, Spanish, Italian, and Dutch),by passing **data-locale** attribute .
this released of stripe not yet supported in this version of angular-stripe-chekout, you can add it by adding this property 
  **locale:"data-locale"**  to **COPIED_OPTION_ATTRIBUTES**  object in **angular-stripe-chekout.js**

**Comment by tobyn** [comment]
Added in the latest version. Thanks for the report.
