### ISSUE TITLE
Interpolated zip code gives a TypeError by Stripe

### ISSUE THREAD

**Issue by sdeprez** [tobyn/angular-stripe-checkout#19]
Similar to #18, `data-zip-code="true"` is not correctly parsed as a boolean and so yields a TypeError

```
StripeCheckout.configure: Type mismatch for option 'zipCode':
Looking for type 'boolean', but instead we found 'string'.
You can learn about the available configuration options in the Checkout docs:
https://stripe.com/docs/checkout
```

An easy fix is to move [this line](https://github.com/tobyn/angular-stripe-checkout/blob/master/angular-stripe-checkout.js#L19) to the the `BOOLEAN_OPTION_ATTRIBUTES` just below.

Anyway thanks for your library, very convenient to use!

**Comment by KrisBraun** [comment]
Works great, thanks!
