### ISSUE TITLE
iOS mobile Safari thinks Stripe checkout is an undesirable pop-up. 

### ISSUE THREAD

**Issue by Grafrajohn** [tobyn/angular-stripe-checkout#20]
On Latest versions of Safari on iOS 9 the Safari mobile browser we are getting an error thrown by mobile Safari, which thinks the Stripe checkout is an undesirable pop-up and blocks it. Disabling the pop-up blocker solves the problem but we can hardly expect our users to do this.

**Comment by tobyn** [comment]
I just ran through both examples on an iPhone and iPad running iOS 9.3.4 without any problems. If you're not using the stripe-checkout directive, make sure you're calling handler.open() synchronously in response to user input ([see here](https://stripe.com/docs/checkout#integration-more-runloop)).

If you're obeying this restriction, it's still not working, and you have a test case that I can use to debug, I'm happy to take another look.
