### ISSUE TITLE
Issues with directive

### ISSUE THREAD

**Issue by cdvv7788** [tobyn/angular-stripe-checkout#21]
The StripeCheckoutDirective was raising some issues when i used it in my angular application loading key from the scope. The issue did not happen the first time i loaded the view, but after i left it and came back. The issue was that the key that was being loaded was "{{ my_key }}".
I fixed this by adding a $timeout() to the directive.

**Comment by georgi-kovachev** [comment]
hi @cdvv7788 how do you add $timeout to the directive? I am having same issue

**Comment by MileanCo** [comment]
Im also having this issue... pretty strange.

**Comment by MileanCo** [comment]
@cdvv7788 I created a pull request with the fix you suggested, I tested it and it works :)
https://github.com/tobyn/angular-stripe-checkout/pull/27
