### ISSUE TITLE
Browserify not working - Wrong main file in package.json

### ISSUE THREAD

**Issue by paneyi** [tobyn/angular-stripe-checkout#5]
Hi @tobyn, awesome work allowing npm/browserify, it was exactly what I needed!
However, when trying to use it I've got an error and I was able to track it to package.json having a wrong value in the main key: it says 'index.js' where it should be 'angular-stripe-checkout.js'.

Thanks for your hard work!

**Comment by tobyn** [comment]
Derp. Thanks for the report. This is fixed in 2.2.1.
