### ISSUE TITLE
Any error catch if the Stripe Checkout window did not pop up?

### ISSUE THREAD

**Issue by hughred22** [tobyn/angular-stripe-checkout#6]
So I am running this strange error. The Stripe Checkout windows something does not pop up (using your custom code example). In the error window log: 

Error: Unable to communicate with Checkout. Please contact support@stripe.com if the problem persists.
sendMessage@https://checkout.stripe.com/checkout.js:1:48617
https://checkout.stripe.com/checkout.js:1:15530
https://checkout.stripe.com/checkout.js:1:47580
ready@https://checkout.stripe.com/checkout.js:1:47850
invoke@https://checkout.stripe.com/checkout.js:1:47521
https://checkout.stripe.com/checkout.js:1:15530
close@https://checkout.stripe.com/checkout.js:2:52386
.... ....

I have no idea what is causing this. Is there a error callback if the handler.open fail? Like I click the button that has ng-click, for some reason the window does not open. I can use a toaster message to tell user there is something wrong and try it again?

**Comment by tobyn** [comment]
I'm not aware of a way to intercept errors thrown by Stripe Checkout, and I don't see anything in the docs about it. I know it has some undocumented options, though, so if you find anything let me know and I'll be happy to add whatever support I can.
